In [ ]:
import numpy as np

# **Ones, zeros and empty**

In [ ]:
#Create an empty numpy array
arr = np.empty((2,3))
arr

array([[4.89656118e-310, 0.00000000e+000, 2.05833592e-312],
       [6.79038654e-313, 2.14321575e-312, 2.27053550e-312]])

In [ ]:
arr = np.empty(2)  # 1d array
arr

array([2.0000000e+000, 6.6761277e-310])

In [ ]:
arr = np.ones(2) # 1 d
arr

array([1., 1.])

In [ ]:
arr = np.ones((2,3)) # multiple dim
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr = np.zeros(2)
arr

array([0., 0.])

In [ ]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

# Check if a row in contained in a numpy array - a numpy array has .tolist()

In [ ]:
arr = np.array([[1,2,3,4,5],
       [6,7,8,9,10],
       [11,12,13,14,15]])

print([1,2,3,4,5] in arr.tolist())

True


# Remove all rows containing non-numeric elements

In [39]:
arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
print(arr[np.invert(np.isnan(arr).any(axis=1))])

[[10.5 22.5  3.8]]


OR

In [40]:
arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
print(arr[~np.isnan(arr).any(axis=1)])

[[10.5 22.5  3.8]]


## LOL, this is a way to remove all np.nan


In [45]:
arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])


In [44]:
#My own
#Change all nan's to zeroes
arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])

arr[arr != arr] = 0

print(arr)

[[10.5 22.5  3.8]
 [41.   0.   0. ]]


# Compress / squeeze your array to a smaller dim

In [47]:
arr=[[[1,2,3]]]
print(np.squeeze(arr))

[1 2 3]


# arange function to initialize array

In [53]:
arr = np.arange(3)
print(arr)
arr1 = np.arange(1,6,2) # Start, end and skip
print(arr1)

[0 1 2]
[1 3 5]


# reshape func - very Important

In [58]:
arr = np.arange(10)
print(arr.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


OR

In [61]:
arr = np.arange(10)
print(np.reshape(arr,(2,5)))

[[0 1 2 3 4]
 [5 6 7 8 9]]


Number of occurences of a sequence in a numpy array

In [83]:
arr = np.array([[2, 8, 9, 4],
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, np.nan]])
output=repr(arr).count("9, 4")
output
#Just me trying
print(arr.reshape(-1,1).squeeze())

[ 2.  8.  9.  4.  9.  4.  9.  4.  4.  5.  9.  7.  2.  9.  4. nan]


# COMPRESS

This is just too cool - [0,1] axis 1 -> omits first columns and fetches the 2nd column only

In [91]:
arr = [[1,2],
       [3,4],
       [5,6]]

print(np.compress([0,1],arr,axis=1))

[[2]
 [4]
 [6]]


# BINCOUNT

Find the most frequent value in a NumPy array - returns a count array till max ( a small step similar to the counting sort )

In [100]:
arr = [1,2,3,1,2,42,1,3,4,1,2,3,2,3,4,5,1,1,1,2,3,4,5,7]
print(np.bincount(arr))
print(np.bincount(arr)[np.bincount(arr).argmax()],":",np.bincount(arr).argmax())

[0 7 5 5 3 2 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1]
7 : 1


# COMBINING 2 ARRAYS

If a 1d array gets fully traversed, then second row of 2d array re-prints the 1d with itself for another iteration

In [112]:
num_1d = np.arange(5)
print("One dimensional array:")
print(num_1d)

num_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array:")
print(num_2d)

for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b),)

One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


In [122]:
array_1 = np.array([1, 2])
array_2 = np.array([4, 6])
np.meshgrid(array_1,array_2)

[array([[1, 2],
        [1, 2]]),
 array([[4, 4],
        [6, 6]])]

# Add a pad for the actual array

In [128]:
array = np.ones((2, 2))

print("Original array")
print(array)

print("\n0 on the border and 1 inside the array")
array = np.pad(array, pad_width=1,constant_values=9)

print(array)

Original array
[[1. 1.]
 [1. 1.]]

0 on the border and 1 inside the array
[[9. 9. 9. 9.]
 [9. 1. 1. 9.]
 [9. 1. 1. 9.]
 [9. 9. 9. 9.]]
