In [25]:
import numpy as np
import pandas as pd

In [26]:
irisData = pd.read_csv('iris.data')
X = irisData.iloc[:,:-1:].values
Y = irisData.iloc[:,-1].values
print(Y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versic

In [27]:
import numpy as np
print(X)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.

In [48]:
class MyPerceptron:
    def __init__(self,epochs=100,lr=0.01):
        self.epochs = epochs
        self.lr = lr
        self.weights = None
        self.bias = None
    
    def fit(self,X,y):
        rows,columns = X.shape
        self.weights = np.zeros(columns)
        self.bias = 0
        for epoch in range(self.epochs):
            for i in range(rows):
                y_pred = self.Activation(np.dot(self.weights,X[i])+self.bias)
                self.weights += (self.lr*(y[i] - y_pred)*X[i])
                self.bias += (self.lr*(y[i] - y_pred))
    
    def Activation(self,y):
        if y>0:
            return 1
        else:
            return 0
    
    def predict(self,X):
        y_preds = []
        for i in range(X.shape[0]):
            y_pred = self.Activation(np.dot(self.weights,X[i])+self.bias)
            y_preds.append(y_pred)
        return y_preds

In [33]:
class Perceptron:
    def __init__(self,lr=0.1,epochs=1000):
        self.lr = lr
        self.epochs = epochs
        self.weights = None
        self.bias = None
    
    def fit(self,X,y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0
        for epoc in range(self.epochs):
            for i in range(X.shape[0]):
                y_pred = self.Activation(np.dot(self.weights,X[i]) + self.bias)
                self.weights+=(self.lr*(y[i]-y_pred)*X[i])
                self.bias+=(self.lr*(y[i]-y_pred))
    
    def Activation(self,y):
        if y>0:
            return 1
        else:
            return 0
    
    def predict(self,X):
        y_pred = []
        for i in range(X.shape[0]):
            y_pred.append(self.Activation(np.dot(self.weights,X[i]) + self.bias))
        return y_pred

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler


def myPredictorFunction(X,Y,predictVal):
    X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)
    # print(X_train)
    # print(Y_train)
    
    perceptron = MyPerceptron()
    perceptron.fit(X_train,Y_train)
    y_pred = perceptron.predict(predictVal)
    return y_pred



In [49]:
irisSetosa = np.where(Y == "Iris-setosa",1,0)
irisVersicolor = np.where(Y == "Iris-versicolor",1,0)
irisVirginica = np.where(Y == "Iris-virginica",1,0)
l=[irisSetosa,irisVersicolor,irisVirginica]
predictVal=np.array([[4.9,3.0,1.4,0.2]])
result=[]
resultAsAString=""
for i in l:
    pre = myPredictorFunction(X,i,predictVal)
    result.extend(pre)
for i in result:
    resultAsAString+=str(i)
print(resultAsAString)
if(resultAsAString=="100"):
    print("Setosa")
elif(resultAsAString=="010"):
    print("Versicolor")
else:
    print("Virginica")

100
Setosa


In [10]:
class LogisticRegression:
    def __init__(self,learning_rate = 0.01,num_iterations = 1000):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations
    
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))
    
    def fit(self,X,Y):
        num_samples,num_features = X.shape
        print(num_samples,num_features)
        self.weights = np.zeros(num_features)
        self.bias = 0

        for i in range(self.num_iterations):
            Y_pred = self.predicted(X)
            dw = (1/num_samples)*np.dot(X.T,(Y_pred - Y))
            db = (1/num_samples)*np.sum(Y_pred - Y)
            
            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate*db
            
    def predicted(self,X):
        linear_model = np.dot(X,self.weights)+self.bias
        pred = self.sigmoid(linear_model)
        return pred
    
    def test(self,X,Y):
        global Y_predtest
        Y_predtest = self.predicted(X)
        print(Y_predtest)
        Y_values = Y_predtest
        correct = 0
        total = len(Y)
        for i in range(len(Y_predtest)):
            if Y_predtest[i]>0.5:
                Y_predtest[i] =1
            else:
                Y_predtest[i]=0
        for i in range(len(Y)):
            if Y[i] == Y_predtest[i]:
                correct+=1
        print("Accuracy: ",correct/total) 
                